// <auto-generated />
using MVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221114103507_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC.Models.Person", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = "d815227d-6760-4a61-bf4c-d0eb493aef07",
                            City = "Gothenburg",
                            Name = "Hilda",
                            PhoneNumber = "0756845297"
                        },
                        new
                        {
                            Id = "e55722c3-75bd-442e-b9f2-17717becd9ad",
                            City = "Stockholm",
                            Name = "Berit",
                            PhoneNumber = "0735648701"
                        },
                        new
                        {
                            Id = "3c1dd2bc-bd4d-4d90-8144-4112b682b96a",
                            City = "Karlstad",
                            Name = "Albert",
                            PhoneNumber = "0765487028"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
